// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook'
import reactHooks from 'eslint-plugin-react-hooks'

//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  {
    ignores: [
      'storybook-static/**',
      'debug-storybook.log',
      '**/*.test.ts',
      '**/*.test.tsx',
      // Generated by `npm run db:types`
      'src/shared/types/database.types.ts',
      // Not in tsconfig.json — type-aware linting cannot parse these.
      'e2e/**',
      '**/*.stories.ts',
      '**/*.stories.tsx',
      'playwright.config.ts',
      'vitest.integration.config.ts',
      'src/test/integration/**',
      'scripts/**',
      'eslint.config.js',
      'prettier.config.js',
    ],
  },
  ...tanstackConfig,
  ...storybook.configs['flat/recommended'],
  {
    plugins: {
      'react-hooks': reactHooks,
    },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      // Keep registered so existing disable comments are valid. Warn rather than
      // error so historical effects that were never linted do not fail CI.
      'react-hooks/exhaustive-deps': 'warn',
      // Supabase generated types treat post-error `data` as non-null, and control-flow
      // narrowing makes many runtime guards look redundant. Those checks are still
      // useful against actual API payloads; the rule is too noisy here.
      '@typescript-eslint/no-unnecessary-condition': 'off',
    },
  },
]
